server:
  port: 8089

spring:
  application:
    name: techwhisky-spring-cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nitinvarshney1983/config-repo.git
          skipSslValidation: true
          default-label: master #if client do not define branch label
  security:
    user:
      name: root #fixed user
      password: s3cr3t # providing basic authentication. we can make it more complex. by default spring generate a password.