server:
  port: 8089

spring:
  application:
    name: techwhisky-spring-cloud-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nitinvarshney1983/config-repo.git
          skipSslValidation: true
          default-label: master